### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by ngosang** [matusnovak/prometheus-smartctl#18]
Do you have any Grafana Dashboard to share?

**Comment by nvtkaszpir** [comment]
something like this?
![smartctl_test-fs8](https://user-images.githubusercontent.com/1480252/162321612-83706928-d8f8-4ed4-8542-f6440bb0805e.png)

**Comment by ngosang** [comment]
I made my own dashboard. You can download it from here => [dashboard.txt](https://github.com/matusnovak/prometheus-smartctl/files/8481335/dashboard.txt)

I don't know if it will be useful for others but you can make a folder in this repository with both dashboards.

![image](https://user-images.githubusercontent.com/10577978/163178592-01a31037-fa7f-4fbe-9c09-761c40605832.png)
