### ISSUE TITLE
Publish Docker images for ARM architecture 

### ISSUE THREAD

**Issue by ngosang** [matusnovak/prometheus-smartctl#19]
It's easy with Docker buildx. I'm doing it in some of my projects with GitHub actions => https://github.com/ngosang/docker-amule/blob/master/.github/workflows/release-docker.yml#L49

Requested archs:
* linux/arm/v7  => arm32
* linux/arm64/v8  => arm64

**Comment by PhilipMay** [comment]
Hi @ngosang - maybe you want to check this project here: https://github.com/PhilipMay/smart-prom-next

It provides these platforms: `linux/386, linux/amd64, linux/arm/v5, linux/arm/v7, linux/arm64/v8`

See here: https://github.com/PhilipMay/smart-prom-next/pkgs/container/smart-prom-next

There is a tab called "OS /Arch" where you can see the provided platform images:

![image](https://user-images.githubusercontent.com/229382/174682314-67ac15c2-5a4f-4ed9-b7de-ea84befaaf16.png)

**Comment by PhilipMay** [comment]
@ngosang if you tested it - feedback would be very welcome...

**Comment by ngosang** [comment]
@matusnovak If you don't have time to maintain this project you can make me or @PhilipMay maintainers. There is no point in having 2 forks with very few users each one.

@PhilipMay I tested you image but it's not working for me. I will open some issues in your project.

**Comment by PhilipMay** [comment]
> @matusnovak If you don't have time to maintain this project you can make me or @PhilipMay maintainers. There is no point in having 2 forks with very few users each one.

I don't consider this a fork. It is a standalone development.

> @PhilipMay I tested you image but it's not working for me. I will open some issues in your project.

Yes. Sure - many thanks for the issues. Please provide detailed infos.

**Comment by matusnovak** [comment]
Hi @ngosang and @PhilipMay 

I apologise for such long delay. I had a time difficult few months and I really wish I had more time for GitHub.

Making you into a maintainer is a good idea. Are you both ok with you both being the repo maintainers?

**Comment by PhilipMay** [comment]
I generally agree.

However, to be honest:

I personally think that my own fundamentally new implementation is better. Otherwise I would not have started it.

So I'll really actively maintain my own implementation.

**Comment by matusnovak** [comment]
I understand. This project started as something stupid simple that did the job. I have never planned that this would become more useful to other people.

I have added you both to this repo, you should have an invite.

You are free to change the implementation. Also feel free to change the readme to point anyone who stumbles upon this repo to link to your more better implementation.

And many thenks for all of your PRs and issues. And I am sorry I was not able to work on this project.

**Comment by PhilipMay** [comment]
@matusnovak ok cool. Many thanks for your trust.

@ngosang I would love to have a conversation with you about: 
"How we can handle this repo, my repo, and the maintenance?"

Is it ok if I set up a 30 min MS Teams or WebEx Teams chat with us?
Your Mail is [removed for spam protection] - right?

**Comment by ngosang** [comment]
@matusnovak I don't have much time lately but I forked this Prometheus exporter to use it in my infrastructure. I prefer to maintain this repository than my fork, at least I can get contributions back. If you agree I can do the following:
* I'm going to review and merge all open PRs/issues but I don't plan to implement new features, just bug fixing and security updates
* At least 1 change breaks compatibility so I will release version 2.0.0 => #13

@PhilipMay Thank you for your work. I didn't see your project was a new implementation. Since it requires some changes to work in my infrastructure and I have some Grafana dashboards and Prometheus rules coupled to this project I prefer to keep using this project for now. If your project gains popularity I will move eventually... Please, remove my email (spam bots)

**Comment by PhilipMay** [comment]
> Please, remove my email (spam bots)

I will do that.
Your mail is visible for all spam bots on your GitHub profile page by the way.

**Comment by ngosang** [comment]
Release v2.0.0 published
https://github.com/matusnovak/prometheus-smartctl/releases/tag/v2.0.0
https://hub.docker.com/r/matusnovak/prometheus-smartctl/tags?page=1&name=v2.0.0

I'm running it in my servers (ARM + x64)

@Jopaul-John @slavonicsniper @yosh-se
