### ISSUE TITLE
Replace sleep code

### ISSUE THREAD

**Issue by PhilipMay** [matusnovak/prometheus-smartctl#24]
IMO this code:

https://github.com/matusnovak/prometheus-smartctl/blob/3fbd7bbb06b466bfeb7c1eb99aec45a5951f1458/smartprom.py#L176-L184

can be replaced by just this:

```python
    while True:
        collect()
        time.sleep(20)
```

What do you think?

**Comment by ngosang** [comment]
Closed by #29
