### ISSUE TITLE
Why do you not use json output for sat devices?

### ISSUE THREAD

**Issue by PhilipMay** [matusnovak/prometheus-smartctl#25]
Hi,

for all but sat devices you use "json" output like this:
https://github.com/matusnovak/prometheus-smartctl/blob/3fbd7bbb06b466bfeb7c1eb99aec45a5951f1458/smartprom.py#L92

Why dont you use it for sat? Would that be an improvement?
https://github.com/matusnovak/prometheus-smartctl/blob/3fbd7bbb06b466bfeb7c1eb99aec45a5951f1458/smartprom.py#L61

**Comment by ngosang** [comment]
PRs are welcome!

**Comment by ngosang** [comment]
https://github.com/matusnovak/prometheus-smartctl/releases/tag/v2.0.1
