### ISSUE TITLE
Grafana Dashboard ?

### ISSUE THREAD

**Issue by bkiziltas41** [matusnovak/prometheus-smartctl#3]
Hi, 
While i was looking for a script for smartctl, i found your excellent work and get the metrics easily with prometheus. But i could not find a suitable grafana dashboard for this.  Is there any plan to make a grafana dashboard for this work.

Thanks

**Comment by matusnovak** [comment]
Hi @bkiziltas41,

I am afraid I do not have a suitable dashboard for this, and I don't plan on creating one in the near future. Sorry.

I personally only use it to get the temperature values as shown below.

![image](https://user-images.githubusercontent.com/10331278/98598279-8389e780-22da-11eb-95e0-52e8d6ae2a5a.png)

Configured simply as:

![image](https://user-images.githubusercontent.com/10331278/98598288-85ec4180-22da-11eb-8ffa-7f4f24fd92cd.png)

**Comment by stemid** [comment]
My friend @Kybeer just told me he published a dashboard for this exporter: https://grafana.com/grafana/dashboards/14062
