### ISSUE TITLE
Duplicated timeseries in CollectorRegistry: {'smartprom_power_on_hours'}

### ISSUE THREAD

**Issue by tylercranston** [matusnovak/prometheus-smartctl#36]
Since upgrading to v2.0.0 I am seeing the following error in the logs:

Exception: Duplicated timeseries in CollectorRegistry: {'smartprom_power_on_hours'}

Devices and its types {'/dev/sda': 'sat', '/dev/sdc': 'sat', '/dev/sdd': 'sat', '/dev/sde': 'sat', '/dev/sdf': 'sat', '/dev/sdg': 'sat', '/dev/nvme0': 'nvme'}
Server listening in http://0.0.0.0:9902/metrics
Adding new gauge smartprom_reallocated_sector_ct (0x5)
Adding new gauge smartprom_reallocated_sector_ct_raw (0x5)
Adding new gauge smartprom_power_on_hours (0x9)
Adding new gauge smartprom_power_on_hours_raw (0x9)
Adding new gauge smartprom_power_cycle_count (0xc)
Adding new gauge smartprom_power_cycle_count_raw (0xc)
Adding new gauge smartprom_wear_leveling_count (0xb1)
Adding new gauge smartprom_wear_leveling_count_raw (0xb1)
Adding new gauge smartprom_used_rsvd_blk_cnt_tot (0xb3)
Adding new gauge smartprom_used_rsvd_blk_cnt_tot_raw (0xb3)
Adding new gauge smartprom_program_fail_cnt_total (0xb5)
Adding new gauge smartprom_program_fail_cnt_total_raw (0xb5)
Adding new gauge smartprom_erase_fail_count_total (0xb6)
Adding new gauge smartprom_erase_fail_count_total_raw (0xb6)
Adding new gauge smartprom_runtime_bad_block (0xb7)
Adding new gauge smartprom_runtime_bad_block_raw (0xb7)
Adding new gauge smartprom_uncorrectable_error_cnt (0xbb)
Adding new gauge smartprom_uncorrectable_error_cnt_raw (0xbb)
Adding new gauge smartprom_airflow_temperature_cel (0xbe)
Adding new gauge smartprom_airflow_temperature_cel_raw (0xbe)
Adding new gauge smartprom_ecc_error_rate (0xc3)
Adding new gauge smartprom_ecc_error_rate_raw (0xc3)
Adding new gauge smartprom_crc_error_count (0xc7)
Adding new gauge smartprom_crc_error_count_raw (0xc7)
Adding new gauge smartprom_por_recovery_count (0xeb)
Adding new gauge smartprom_power_off_retract_count (0xc0)
Adding new gauge smartprom_power_off_retract_count_raw (0xc0)
Adding new gauge smartprom_load_cycle_count (0xc1)
Adding new gauge smartprom_load_cycle_count_raw (0xc1)
Adding new gauge smartprom_temperature_celsius (0xc2)
Adding new gauge smartprom_temperature_celsius_raw (0xc2)
Adding new gauge smartprom_reallocated_event_count (0xc4)
Adding new gauge smartprom_reallocated_event_count_raw (0xc4)
Adding new gauge smartprom_current_pending_sector (0xc5)
Adding new gauge smartprom_current_pending_sector_raw (0xc5)
Adding new gauge smartprom_offline_uncorrectable (0xc6)
Adding new gauge smartprom_offline_uncorrectable_raw (0xc6)
Adding new gauge smartprom_udma_crc_error_count (0xc7)
Adding new gauge smartprom_udma_crc_error_count_raw (0xc7)
Adding new gauge smartprom_calibration_retry_count (0xb)
Adding new gauge smartprom_calibration_retry_count_raw (0xb)
Adding new gauge smartprom_multi_zone_error_rate (0xc8)
Adding new gauge smartprom_multi_zone_error_rate_raw (0xc8)
Adding new gauge smartprom_critical_warning (0x0)
Adding new gauge smartprom_temperature (0x33)
Adding new gauge smartprom_available_spare (0x64)
Adding new gauge smartprom_available_spare_threshold (0x32)
Adding new gauge smartprom_percentage_used (0x8)
Adding new gauge smartprom_data_units_read (0x1ca0e8a)
Adding new gauge smartprom_data_units_written (0x3d9497e)
Adding new gauge smartprom_host_reads (0xd7b95ba)
Adding new gauge smartprom_host_writes (0x1d7a4025)
Adding new gauge smartprom_controller_busy_time (0x2105)
Adding new gauge smartprom_power_cycles (0x9c)
Adding new gauge smartprom_power_on_hours (0x324)
Exception: Duplicated timeseries in CollectorRegistry: {'smartprom_power_on_hours'}
Adding new gauge smartprom_power_on_hours (0x324)
Exception: Duplicated timeseries in CollectorRegistry: {'smartprom_power_on_hours'}
Adding new gauge smartprom_power_on_hours (0x324)
Exception: Duplicated timeseries in CollectorRegistry: {'smartprom_power_on_hours'}

**Comment by ngosang** [comment]
https://github.com/matusnovak/prometheus-smartctl/releases/tag/v2.0.1
