### ISSUE TITLE
High IO spikes during polls

### ISSUE THREAD

**Issue by payne0420** [matusnovak/prometheus-smartctl#49]
My SAS drives don't seem to be so happy getting polled. Is there anything I can do to avoid this?
The host has 32x Seagate SAS drives

![image](https://github.com/matusnovak/prometheus-smartctl/assets/10525363/dcce9cfd-1f61-4af4-999f-8365a1a23207)

**Comment by ngosang** [comment]
We are using the smartctl tool and we can't reduce the I/O usage.
You can set the env var `SMARTCTL_REFRESH_INTERVAL` to a higher value to reduce the load.
